@echo off
echo "     .--''''"
echo "  .'      .-"
echo " /    .-----"
echo "/        .--"
echo "|       .-. "
echo "|      /   \"
echo " \    | .-. "
echo "  '-._| | | "
echo "      | '-' "
echo "       \___/"
echo "    _.-'  / "
echo "  .' _.--|  "
echo "  ' _...-|  "
echo "         |  "
echo "         '._"
echo "           |"
echo "          _|"
echo "         /\("
echo "        /  `"
echo "       | |  "
echo "       '-'  "
echo "       | |  "
echo "       | |  "
echo "       | |--"
echo "    .`/  |  "
echo "    |    |  "
echo "    '._.'| ."
echo "          \ "
echo "          | "
echo "          | "
echo "          | "
echo "         /| "
echo "       .'_| "
echo "    .    /  "
echo "   /o`.-'  /"
echo "  /o  o\ .' "
echo "  `.___.'   "
