@echo off
echo "     .--'''''''''--.     "
echo "  .'      .---.      '.  "
echo " /    .-----------.    \ "
echo "/        .-----.        \"
echo "|       .-.   .-.       |"
echo "|      /   \ /   \      |"
echo " \    | .-. | .-. |    / "
echo "  '-._| | | | | | |_.-'  "
echo "      | '-' | '-' |      "
echo "       \___/ \___/       "
echo "    _.-'  /   \  `-._    "
echo "  .' _.--|     |--._ '.  "
echo "  ' _...-|     |-..._ '  "
echo "         |     |         "
echo "         '.___.'         "
echo "           | |           "
echo "          _| |_          "
echo "         /\( )/\         "
echo "        /  ` '  \        "
echo "       | |     | |       "
echo "       '-'     '-'       "
echo "       | |     | |       "
echo "       | |     | |       "
echo "       | |-----| |       "
echo "    .`/  |     | |/`.    "
echo "    |    |     |    |    "
echo "    '._.'| .-. |'._.'    "
echo "          \ | /          "
echo "          | | |          "
echo "          | | |          "
echo "          | | |          "
echo "         /| | |\         "
echo "       .'_| | |_`.       "
echo "    .    /  |  \    .    "
echo "   /o`.-'  / \  `-.`o\   "
echo "  /o  o\ .'   `. /o  o\  "
echo "  `.___.'       `.___.'  "
:squidRave
    color 07
    color 70
goto squidRave
